Sprint8
Jlogblpb/go-db-sql-final pull request #1
Opened 2024-02-20 19:25 UTC by Jlogblpb

2024-02-21 10:11 UTC, just-musha requested changes
Привет! Неплохо!

Предлагаю тебе сразу 3 момента важных поправить:

1. в методах убрать открытие соединения с БД (смотри комментарий в ревью)
2. возвращать пустой массив и ошибку там где сейчас ты возвращаешь nil
3. В самом последнем тесте - проверь как обращаешься к элементу мапы

Вот. Жду правки!

2024-02-21 10:11 UTC, just-musha commented on parcel.go
> +	db, err := sql.Open("sqlite", "tracker.db")
Важный момент - сейчас в каждом методе заново открываешь соединение с БД. 
Но у тебя оно уже открыто - в функции `main`, и лежит в `s.db`

И здесь ты уже можешь сразу обращаться к базе через `s.db`
Поэтому давай уберем вызов Open из всех методов

2024-02-21 10:11 UTC, just-musha commented on parcel.go
> +		return nil, nil
Странно, что возвращаются nil, если случилась ошибка.
Давай вернем ошибку все-таки и пустой пассив Parsel? А то сейчас будет выглядеть как будто все успешно прошло
`return res, err`
 
(только `var res []Parcel` нужно будет повыше вынести)

2024-02-21 10:11 UTC, just-musha commented on parcel.go
> +			return nil, nil
И здесь тоже

`return res, err`

2024-02-21 10:11 UTC, just-musha commented on parcel_test.go
> +		assert.NotEmpty(t, parcelMap(parcel))
Здесь не хватает проверок, нужно сравнить поля у parcel и посылки которая лежит в мапе.

Обрати внимание как ты получаешь элемент из мапы, повтори этот момент. Нужно получать по id:
`parcelMap[parcel.Number]`

2024-02-21 11:35 UTC, Jlogblpb commented on parcel_test.go
> +		assert.NotEmpty(t, parcelMap(parcel))
По идее, мы считываем в запросе  из таблицы только столбец "number", т.о. получается мы можем сравнить только идентификаторы посылок. Я же правильно понял? Если да то дописал..

2024-02-21 12:41 UTC, just-musha requested changes
Давай все поля получим и сравним.
И ещё - сейчас код не компилируется. Можешь проверить починить, чтобы тесты все запускались и проходили?

2024-02-21 12:41 UTC, just-musha commented on parcel_test.go
> +	storedParcels, err := s.db.Query("SELECT number FROM parcel WHERE client = :client",
А, вижу - пропустила этот момент. Нам надо все поля посылки проверить. Давай запросим их тоже, а ниже - сравним

> убедитесь, что значения полей полученных посылок заполнены верно

2024-02-22 07:44 UTC, just-musha requested changes
Вижу что файл с тестами `parcel_test.go` полностью удален, возможно случайно. Добавишь исправленную версию?

2024-02-22 10:33 UTC, Jlogblpb commented
Не понимаю как произошло. Отправил, проверил, вроде бы все файлы на месте.

2024-02-22 13:17 UTC, just-musha commented
Вижу что тесты не компилируются сейчас, есть ошибки. Необходимо разобраться с ними, чтобы тесты запустились. Если есть вопросы, смело задавай наставнику.
Перед отправкой на ревью убедись, что тесты запускаются и проходят.

```
➜  go-db-sql-final-Jlogblpb git:(sprint8) go test ./... 
# github.com/Yandex-Practicum/go-db-sql-final [github.com/Yandex-Practicum/go-db-sql-final.test]
./parcel_test.go:35:2: store declared and not used
./parcel_test.go:35:26: undefined: s
./parcel_test.go:42:20: undefined: Add
./parcel_test.go:51:18: undefined: Get
./parcel_test.go:53:27: undefined: parsel
./parcel_test.go:59:6: no new variables on left side of :=
./parcel_test.go:59:9: undefined: Delete
./parcel_test.go:61:15: no new variables on left side of :=
./parcel_test.go:61:18: undefined: Get
./parcel_test.go:63:15: not enough arguments in call to assert.Empty
	have (unknown type)
	want (assert.TestingT, interface{}, ...interface{})
./parcel_test.go:35:2: too many errors
FAIL	github.com/Yandex-Practicum/go-db-sql-final [build failed]
FAIL
```

2024-02-22 13:18 UTC, just-musha requested changes
Вижу что тесты не компилируются сейчас, есть ошибки. Необходимо разобраться с ними, чтобы тесты запустились. Если есть вопросы, смело задавай наставнику.
Перед отправкой на ревью убедись, что тесты запускаются и проходят.

2024-02-25 07:07 UTC, just-musha approved these changes
Супер, сейчас все ок, запускаются тесты и проходят. По коду все хорошо. Отличная работа! Принято.
![42ba760cc603c4c52eba23b535e42bb3](https://github.com/Jlogblpb/go-db-sql-final/assets/23293688/1bfe696f-a332-4262-8026-ee40bc468555)

2024-02-25 07:07 UTC, just-musha commented on parcel_test.go
> +	require.Error(t, err)
Можно ещё ошибку саму проверить, что это `ErrNoRows`

2024-03-03 19:03 UTC, closed without merging